is the host on the network

diff --git a/basics_0/5-is_the_host_on_the_network b/basics_0/5-is_the_host_on_the_network
--- a/basics_0/5-is_the_host_on_the_network
+++ b/basics_0/5-is_the_host_on_the_network
@@ -1,9 +1,20 @@
 #!/usr/bin/env bash
-# a Bash script that pings an IP address passed as an argument.
 
-if [ $# -eq 0 ]
-then
-  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
+# Check if an IP address argument is provided
+if [ $# -ne 1 ]; then
+    echo "Usage: $0 {IP_ADDRESS}"
+    exit 1
+fi
+
+# Get the IP address from the command-line argument
+ip_address="$1"
+
+# Ping the specified IP address 5 times
+ping -c 5 "$ip_address"
+
+# Check the exit status of the ping command
+if [ $? -eq 0 ]; then
+    echo "Ping to $ip_address was successful."
 else
-  ping -c 5 "$1"
+    echo "Ping to $ip_address failed."
 fi
